---
title: "generalized_ookla_download"
output: html_document
date: "2023-01-13"
---

# Reference https://github.com/teamookla/ookla-open-data/blob/master/tutorials/aggregate_by_county.md

```{r}
library(tigris) # county boundaries
library(tidyverse) # data cleaning
library(sf) # spatial functions
library(knitr)
library(kableExtra) # county statistics table
library(RColorBrewer) # colors
library(here) # file management
library(usethis) # download data
library(mapview)
library(data.table)
```


# Check if file exist. If not, download data
```{r}

ookla_shape_file_loc <- here("legacy/code/temp/2020-04-01_performance_fixed_tiles/gps_fixed_tiles.shp")

file.exists(ookla_shape_file_loc)

if (!file.exists(ookla_shape_file_loc)){
  # download the zip folder from s3 and save to working directory
  use_zip("https://ookla-open-data.s3-us-west-2.amazonaws.com/shapefiles/performance/type%3Dfixed/year%3D2020/quarter%3D2/2020-04-01_performance_fixed_tiles.zip")
}

#read the shapefile. 
tiles <- read_sf(ookla_shape_file_loc) %>%
  mutate(avg_d_kbps = as.numeric(avg_d_kbps),
         avg_u_kbps = as.numeric(avg_u_kbps),
         avg_lat_ms = as.numeric(avg_lat_ms))
```

# Get county boundaries
```{r}

# states <- state.name
# state.abb

get_bg_state <- function(state, year=2019, variable="B01003_001", samples= 10000){

  
  counties <- tigris::counties(state = state) %>%
    select(state_code = STATEFP, geoid = GEOID, name = NAME) %>% # only keep useful variables 
    st_transform(4326) # transform to the same CRS as the tiles
  
  if (!is.null(samples)){
      tile_subset <- tiles[sample(nrow(tiles), samples), ] # create smaller sample for testing
  
  }else{
    tile_subset <- tiles
  }
  county_tiles <- st_join(counties, tile_subset, left=FALSE)
  return(county_tiles)
}

```

```{r}

combined <- NULL
for (abb in state.abb)
  if (is.null(combined)){
    combined <- get_bg_state(abb, samples=NULL)
  } else{
    combined <- rbind(combined, get_bg_state(abb, samples=NULL))
  }

mapview(combined, zcol="avg_d_kbps")
```



